### ISSUE TITLE
Create Performance Evaluation Step 2A - Select Employees Screen

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#27]
**Wireframe:**

![Image](https://github.com/nerubia/kh360-react/assets/54575305/874250e3-d7f8-47ad-ab67-ea64e10000bc)

**Acceptance Criteria:**

- [x] List all employee information that match the search criteria
- [x] Employees should be sorted by last_name and first_name in ascending order
- [x] By default, no filters are set (so all records will be returned but with pagination implemented)
- [x] Display a maximum of 20 records per page
- [x] When Search button is clicked, display records that match the filters
- [x] When Clear button is clicked, clear all filters then do search function (so all records will be returned)

- [x] Name column should be `last_name, first_name` format
- [x] Date started should be yyyy-mm-dd format
- [x] When header checkbox is ticked, select all results displayed within the page (do not include results from other pages)
- [x] When header checkbox is unchecked, deselect all in that page (do not deselect from other pages)
- [x] When `Check and Review Action` is clicked, redirect to `Step 2B - Review Employees Screen`

**Comment by emmaacha** [comment]
PR: #30

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Please correct the label for Search Filter for Name. It should be `Name` only, not `Name/Email`
- [ ] For Date Started Search Results, please display blank instead of `Invalid Date`
- [ ] For Employee Type, is it possible to set display to Proper Format [first letter should be capitalized, same as how it is in the Drop Down search filter for Employee Type]
- [ ] The display should be 20 records per page. Currently, it is showing 18 in first page.



![Image](https://github.com/nerubia/kh360-react/assets/1640285/a3240b46-c543-42da-b0a4-f6994a676f62)

**Comment by emmaacha** [comment]
From what I remember ate @sheilaramas, when Name checkbox is clicked, all employees should be selected. But not entirely sure din, can someone else recall @Dev-Nino @jatnerubia?

**Comment by emmaacha** [comment]
PR: #87
