### ISSUE TITLE
Create Add Evaluator screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#303]
**DESCRIPTION**

This screen is loaded from Eval Admin Step 4 when admin clicks on `Add Evaluator` button (new button).
Screen contains the following fields:

- [x] Dropdown for Template Type (use display names).. show all templates that are active
- [x] Evaluator (typeahead field where user can type name then search from users the matching names?)
- [x] Project (same logic as the project button when adding external evaluators) - can be left blank
          - if project is selected, show the percent_involvement, evaluation start and end dates

Screen will have the following buttons:

- [x] Cancel
- [x] Add

Once Add is clicked, redirect back to Step 4 and display the template where the new evaluator was added. Example, if the admin added PM Evaluation, then go to Step 4, with PM Evaluation selected in the left panel and the evaluators for PM Evaluation shown in the main panel. The newly added evaluator must be displayed there, and checked by default.

If the template was newly added (e.g. originally, there was no Code Reviewer template, but the admin added a Code Reviewer, after clickin add, redirect back to Step 4, with `Code Reviewer Evaluation` now shown in the left panel and the newly added Code Reviewer (checked) in the main panel.

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/315
BE: https://github.com/nerubia/kh360-nodejs/pull/280

**Comment by sheilaramas** [comment]
**ISSUES + ENHANCEMENT**

- [ ] Cannot proceed with project left blank.
- [ ] Please require project data only if the template can be related to a project member record.
- [ ] For templates that are not related to projects (e.g. employee evaluation and hr evaluation), possible to just hide the project dropdown?

- The sample below shows HR Evaluation Template selected but error message is shown.



![Image](https://github.com/nerubia/kh360-react/assets/1640285/04ac12b2-3efa-4c3b-b5f3-c3a940c25f06)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/335
BE: https://github.com/nerubia/kh360-nodejs/pull/306

**Comment by sheilaramas** [comment]
ok verified

**Comment by jasonoperez23** [comment]
Hello @jatnerubia 

Verified OK in Beta
1. Add Evaluator button (new button) is visible in Step 4
2. Dropdown for Template Type (use display names).. show all templates that are active
3. Evaluator (typeahead field where user can type name then search from users the matching names?)
4. Project is selected, show the percent_involvement, evaluation start and end dates
5. Screen will have the following buttons: Cancel and Add
6. Once Add is clicked, redirect back to Step 4 and display the template where the new evaluator was added. The newly added evaluator must be displayed there, and checked by default.

Thanks

**Comment by jasonoperez23** [comment]
Hello @jatnerubia 

NOT OK in Beta
Preconditions:
Account : jason.perez@nerubia.com
Evaluation Period: 2023-12-01 to 2023-12-31

### 1. When adding Evaluator, duplicate projects in `Project` dropdown
![Screen Shot 2024-01-05 at 11 53 29 AM](https://github.com/nerubia/kh360-react/assets/66452971/ee4785ce-8847-4d03-bd54-35f80f058d73)
### 2. Project (same logic as the project button when adding external evaluators) - can be left blank. Unable to proceed if project left blank
![Screen Shot 2024-01-05 at 11 57 49 AM](https://github.com/nerubia/kh360-react/assets/66452971/d93ecb09-f7e4-430c-8a9b-92994e2f366b)

### 3. Duplicate Evaluator names in Step 4 screen (Need to ask @sheilaramas if this is an issue or not)

- This happens when the added evaluator already exist in the evaluator list
![Screen Shot 2024-01-05 at 11 59 14 AM](https://github.com/nerubia/kh360-react/assets/66452971/7d5d4fb9-9c29-4d47-a5c5-935653a84225)

### 4. Unable to remove manually added evaluator and existing evaluators (Need to ask @sheilaramas if this is an issue or not)

### 5. Evaluator field issue (Need to ask @sheilaramas if this is an issue or not)

- recently selected/searched evaluator is displayed first even after clicking cancel

### 6. If the template was newly added (e.g. originally, there was no BOD Evaluation for Project Manager Role, but the admin added a BOD Evaluation for Project Manager Role after clicking add, redirect back to Step 4, with BOD Evaluation for Project Manager Role now shown in the left panel and the newly added BOD Evaluation for Project Manager Role (checked) in the main panel.
Issue: BOD Evaluation for Project Manager Role is displayed in the Main panel but no BOD Evaluation for Project Manager Role shown in the `left panel`

https://github.com/nerubia/kh360-react/assets/66452971/a1ca6b30-8fa0-4ea4-943f-9cb9acb81ee9

**Comment by jasonoperez23** [comment]
Hi @sheilaramas 
Regarding the issues above:

1. When adding Evaluator, duplicate projects in Project dropdown - `For Investigation`
2.  Project (same logic as the project button when adding external evaluators) - can be left blank. Unable to proceed if project left blank - `NOT an issue`
4. Unable to remove manually added evaluator and existing evaluators - `NOT an issue`
5. Evaluator field issue - `Added new ticket`  https://github.com/nerubia/kh360-react/issues/473
6. Missing template in the left panel - `Added new ticket`  https://github.com/nerubia/kh360-nodejs/issues/418


Enhancement
1. Add Evaluator Screen - Change User label to Evaluator #472 - https://github.com/nerubia/kh360-react/issues/472 

Thanks

**Comment by jasonoperez23** [comment]
Closing this ticket
Created new tickets for the issues found

Thanks
